config/routes.rb
Rails.application.routes.draw do
  resources :applications
  resources :comments
  resources :scrim_ads
  root to: 'homes#home'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application.rb
class Application < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :scrim_ad, optional: true
end

app/models/scrim_ad.rb
class ScrimAd < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments, dependent: :destroy
  has_many :scrim_ads, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  require "byebug"
  def new
    @application = Application.new
  end
  
  def create
    @application = Application.new(application_params)
    @application.user_id = current_user.id
    @application.save
    redirect_to "#"
  end
  
  def delete 
  end
  
  def show
  end
  
private 

  def application_params
    params.require(:application).permit!
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  require "byebug"
  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    @comment.scrim_ad_id = params[:scrim_ad]
    @comment.save
    redirect_to scrim_ads_path
  end
  
  private
  
  def comment_params
    params.require(:comment).permit(:description)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def home
  end
end

app/controllers/scrim_ads_controller.rb
class ScrimAdsController < ApplicationController
  require "date"
  require "byebug"
  before_action :authenticate_user!, only: [:new] 
  def index
      @scrim_ads  = ScrimAd.where("scrim_ads.closed > ?", DateTime.now)
      @scrim_ads_delete = ScrimAd.where("scrim_ads.closed < ?", DateTime.now)
      @scrim_ads_delete.destroy_all
  end
  
  def new
    @scrim_ad = ScrimAd.new
  end
  
  def create
    @scrim_ad = ScrimAd.new(scrim_ads_params)
    @scrim_ad.user = current_user
    @scrim_ad.save!
    redirect_to scrim_ads_path
  end
  
  def destroy
    @scrim_ad = ScrimAd.find(params[:id])
    @scrim_ad.destroy
    redirect_to scrim_ads_path, notice: "募集を削除しました。"
  end
  
  def show
    @scrim_ad = ScrimAd.find(params[:id])
    @comments = @scrim_ad.comments
    @comment = Comment.new()
  end
  
  def edit
    @scrim_ad = ScrimAd.find(params[:id])
  end
  
  def update
    @scrim_ad = ScrimAd.find(params[:id])
    @scrim_ad.update(scrim_ads_params)
    redirect_to scrim_ads_path
  end
  
private 

  def scrim_ads_params
    params.require(:scrim_ad).permit!
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/scrim_ads_helper.rb
module ScrimAdsHelper
end

app/views/applications/new.html.erb
<div class = "container">
  <%= form_with model: @application, local: true do |form| %>
  
    <div class = "form-group">
      <%= form.label :member1 %>
      <%= form.text_field :member1, class: "form-control" %>
    </div>
  
    <div class = "form-group">
      <%= form.label :member1 %>
      <%= form.text_field :member1, class: "form-control" %>
    </div>
    
    <div class = "form-group">
      <%= form.label :member2 %>
      <%= form.text_field :member2, class: "form-control" %>
    </div>
    
    <div class = "form-group">
      <%= form.label :member3 %>
      <%= form.text_field :member3, class: "form-control" %>
    </div>
    
    <div class = "form-group">
      <%= form.label :member4 %>
      <%= form.text_field :member4, class: "form-control" %>
    </div>
    
    <div class = "form-group">
      <%= form.label :member5 %>
      <%= form.text_field :member5, class: "form-control" %>
    </div>
    
    <%= form.submit "応募する", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/homes/home.html.erb
<h1>Homes#home</h1>
<%= link_to "sign up", new_user_registration_path, class: "btn btn-primary" %>
<br /><%= link_to "index", scrim_ads_path, class: "btn btn-primary mt-5" %>
<br /><%= link_to "create", new_scrim_ad_path, class: "btn btn-primary mt-5 " %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/scrim_ads/edit.html.erb
<div class = "container">

<%= form_with model: @scrim_ad, local: true do |form| %>
  
  <div class = "form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  
  <div class = "form-group">
    <%= form.label :teamname %>
    <%= form.text_field :teamname, class: "form-control" %>
  </div>
  
  <div class = "form-group">
    <%= form.label :teammember1 %>
    <%= form.text_field :teammember1, class: "form-control" %>
  </div>
  
  <div class = "form-group">
    <%= form.label :teammember2 %>
    <%= form.text_field :teammember2, class: "form-control" %>
  </div>
  
  <div class = "form-group">
    <%= form.label :teammember3 %>
    <%= form.text_field :teammember3, class: "form-control" %>
  </div>
  
  <div class = "form-group">
    <%= form.label :teammember4 %>
    <%= form.text_field :teammember4, class: "form-control" %>
  </div>
  
  <div class = "form-group">
    <%= form.label :teammember5 %>
    <%= form.text_field :teammember5, class: "form-control" %>
  </div>
  
  <div class = "form-group">
    <%= form.label :sabmember1 %>
    <%= form.text_field :sabmember1, class: "form-control" %>
  </div>
  
  <div class = "form-group">
    <%= form.label :sabmember2 %>
    <%= form.text_field :sabmember2, class: "form-control" %>
  </div>

  <div class = "form-group">
    <%= form.label :contact %>
    <%= form.text_field :contact, class: "form-control" %>
  </div>
  
  <div class = "form-group">
    <%= form.label :closed %>
    <%= form.date_field :closed, class: "form-control" %>
  </div>
  
  <div class = "form-group">
    <%= form.label :start_time %>
    <%= form.date_field :start_time, class: "form-control" %>
  </div>
  
  <%= form.submit "編集をする",　class: "btn btn-primary" %>
<% end %>

</div>

app/views/scrim_ads/index.html.erb
<%= flash.notice %>
<% @scrim_ads.each do |info| %>
  <p><%= link_to info.title, scrim_ad_path(info) %></p>
  <p><%= info.teamname %></p>
<%end%>


<p>test</p>

app/views/scrim_ads/new.html.erb
<div class = "container">

<%= form_with model: @scrim_ad, local: true do |form| %>
  
  <div class = "form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  
  <div class = "form-group">
    <%= form.label :teamname %>
    <%= form.text_field :teamname, class: "form-control" %>
  </div>
  
  <div class = "form-group">
    <%= form.label :teammember1 %>
    <%= form.text_field :teammember1, class: "form-control" %>
  </div>
  
  <div class = "form-group">
    <%= form.label :teammember2 %>
    <%= form.text_field :teammember2, class: "form-control" %>
  </div>
  
  <div class = "form-group">
    <%= form.label :teammember3 %>
    <%= form.text_field :teammember3, class: "form-control" %>
  </div>
  
  <div class = "form-group">
    <%= form.label :teammember4 %>
    <%= form.text_field :teammember4, class: "form-control" %>
  </div>
  
  <div class = "form-group">
    <%= form.label :teammember5 %>
    <%= form.text_field :teammember5, class: "form-control" %>
  </div>
  
  <div class = "form-group">
    <%= form.label :sabmember1 %>
    <%= form.text_field :sabmember1, class: "form-control" %>
  </div>
  
  <div class = "form-group">
    <%= form.label :sabmember2 %>
    <%= form.text_field :sabmember2, class: "form-control" %>
  </div>

  <div class = "form-group">
    <%= form.label :contact %>
    <%= form.text_field :contact, class: "form-control" %>
  </div>
  
  <div class = "form-group">
    <%= form.label :closed %>
    <%= form.date_field :closed, class: "form-control" %>
  </div>
  
  <div class = "form-group">
    <%= form.label :start_time %>
    <%= form.date_field :start_time, class: "form-control" %>
  </div>
  
  <%= form.submit "募集を作成する",　class: "btn btn-primary" %>
<% end %>

</div>

app/views/scrim_ads/show.html.erb
<p><%= @scrim_ad.teammember1 %></p>
<p><%= @scrim_ad.teammember2 %></p>
<br /><%= link_to "削除", scrim_ad_path, method: :delete, class: "btn btn-danger" %>
<%= link_to "編集", edit_scrim_ad_path(@scrim_ad), class: "btn btn-success" %>
<%= link_to "応募する", new_application_path(@scrim_ad), class: "btn btn-danger" %>
<% @scrim_ad.comments.each do |comment| %>
  <p><%= comment.user.id %></p>
  <p><%= comment.description %></p>
<%end%>

<%= form_with model: @comment, local: true do |form| %>
  <%= form.label :description %>
  <%= form.text_field :description %>
  <%= hidden_field_tag :scrim_ad, params[:id] %>
  <%= form.submit "コメントする"%>
<%end%>